import { Platform, StyleSheet, StatusBar as NativeStatusBar } from 'react-native';

import type { DelegationTask, DiagnosticLogEntry, GoalSession } from '../types';

export function getDelegationTaskStatusStyle(status: DelegationTask['status']) {
  if (status === 'done') return styles.diagnosticLevelSuccess;
  if (status === 'running' || status === 'pending') return styles.diagnosticLevelWarning;
  if (status === 'error') return styles.diagnosticLevelError;
  return styles.diagnosticLevelInfo;
}


export function getGoalPlanItemStatusStyle(status: GoalSession['planItems'][number]['status']) {
  if (status === 'done') return styles.diagnosticLevelSuccess;
  if (status === 'running' || status === 'todo') return styles.diagnosticLevelWarning;
  if (status === 'blocked') return styles.diagnosticLevelError;
  return styles.diagnosticLevelInfo;
}

export function getDiagnosticLevelStyle(level: DiagnosticLogEntry['level']) {
  if (level === 'success') return styles.diagnosticLevelSuccess;
  if (level === 'warning') return styles.diagnosticLevelWarning;
  if (level === 'error') return styles.diagnosticLevelError;
  return styles.diagnosticLevelInfo;
}

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: '#f5f7fb',
    paddingTop: Platform.OS === 'android' ? NativeStatusBar.currentHeight ?? 0 : 0,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    backgroundColor: '#f5f7fb',
  },
  replyIsland: {
    position: 'absolute',
    top: Platform.OS === 'android' ? (NativeStatusBar.currentHeight ?? 0) + 10 : 10,
    left: '50%',
    zIndex: 50,
    width: 460,
    maxWidth: '80%',
    marginLeft: -230,
    minHeight: 48,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 24,
    backgroundColor: '#111827',
    shadowColor: '#111827',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  replyIslandCompact: {
    left: 16,
    right: 16,
    width: 'auto',
    maxWidth: 'auto',
    marginLeft: 0,
  },
  replyIslandDot: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2563eb',
  },
  replyIslandTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  replyIslandTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  replyIslandPreview: {
    marginTop: 1,
    color: '#cbd5e1',
    fontSize: 12,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  brandBlock: {
    flex: 1,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    color: '#111827',
  },
  subtitle: {
    marginTop: 4,
    color: '#6b7280',
  },
  headerStats: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 8,
  },
  statPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  statPillAccent: {
    borderColor: '#a7f3d0',
    backgroundColor: '#ecfdf5',
  },
  statText: {
    color: '#1f2937',
    fontSize: 12,
    fontWeight: '800',
  },
  statTextAccent: {
    color: '#065f46',
  },
  unreadPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  unreadPillText: {
    color: '#991b1b',
    fontSize: 12,
    fontWeight: '800',
  },
  tabsScroll: {
    flexGrow: 0,
  },
  tabs: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 20,
    paddingBottom: 12,
  },
  runtimeBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginHorizontal: 20,
    marginBottom: 12,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  runtimeBannerOffline: {
    borderColor: '#fed7aa',
    backgroundColor: '#fff7ed',
  },
  runtimeBannerTextBlock: {
    flex: 1,
    gap: 2,
  },
  runtimeBannerTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  runtimeBannerBody: {
    color: '#4b5563',
    fontSize: 12,
    lineHeight: 18,
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 7,
    minHeight: 38,
    paddingHorizontal: 13,
    paddingVertical: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  tabActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  tabText: {
    color: '#4b5563',
    fontWeight: '700',
  },
  tabTextActive: {
    color: '#fff',
  },
  content: {
    flex: 1,
  },
  focusedChatContent: {
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  chatDesktop: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 16,
  },
  chatSidebar: {
    width: 280,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  sidebarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  sidebarTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  sidebarIconButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#eff6ff',
  },
  sidebarRooms: {
    flex: 1,
  },
  sidebarRoomsContent: {
    padding: 8,
    gap: 8,
  },
  sidebarRoom: {
    gap: 6,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#f3f4f6',
    backgroundColor: '#ffffff',
  },
  sidebarRoomActive: {
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  sidebarRoomTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  sidebarRoomTitle: {
    flex: 1,
    color: '#111827',
    fontWeight: '800',
  },
  sidebarRoomTitleActive: {
    color: '#1d4ed8',
  },
  sidebarRoomMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '800',
  },
  sidebarUnreadBadge: {
    overflow: 'hidden',
    minWidth: 22,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 999,
    color: '#ffffff',
    backgroundColor: '#dc2626',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  sidebarRoomPreview: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 17,
  },
  chatMain: {
    flex: 1,
    minWidth: 0,
  },
  focusedChatMain: {
    backgroundColor: '#f8fafc',
  },
  focusedChatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    minHeight: 50,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  focusedBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
    minHeight: 34,
    paddingRight: 8,
  },
  focusedBackText: {
    color: '#111827',
    fontSize: 14,
    fontWeight: '800',
  },
  focusedChatTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  focusedChatTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  focusedChatMeta: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
  },
  focusedDetailsButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  focusedDetailsButtonActive: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  mobileDetailsLayer: {
    position: 'absolute',
    top: 50,
    right: 0,
    bottom: 0,
    left: 0,
    zIndex: 20,
  },
  mobileDetailsBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.18)',
  },
  mobileDetailsCard: {
    position: 'absolute',
    top: 8,
    right: 8,
    bottom: 8,
    width: '88%',
    maxWidth: 390,
    minWidth: 280,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#ffffff',
    shadowColor: '#0f172a',
    shadowOpacity: 0.18,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
    elevation: 10,
    overflow: 'hidden',
  },
  mobileDetailsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f8fafc',
  },
  mobileDetailsScroll: {
    flex: 1,
  },
  mobileDetailsContent: {
    gap: 10,
    padding: 12,
    paddingBottom: 22,
  },
  collabDrawer: {
    width: 310,
    minWidth: 290,
    maxWidth: 340,
    marginRight: 20,
    marginBottom: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  collabDrawerScroll: {
    flex: 1,
  },
  collabDrawerContent: {
    gap: 10,
    padding: 12,
  },
  drawerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 8,
  },
  drawerTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  panel: {
    padding: 20,
    gap: 12,
  },
  mobileRoomPicker: {
    flex: 1,
  },
  mobileRoomPickerContent: {
    gap: 10,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 20,
  },
  mobileRoomPickerHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  mobileRoomCard: {
    gap: 9,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  mobileRoomCardTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  mobileRoomCardFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  roomRail: {
    paddingHorizontal: 20,
    paddingBottom: 8,
  },
  roomRailContent: {
    alignItems: 'center',
    gap: 8,
  },
  roomPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  roomPillActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  roomPillText: {
    color: '#4b5563',
    fontWeight: '700',
  },
  roomPillTextActive: {
    color: '#fff',
  },
  roomUnreadBadge: {
    overflow: 'hidden',
    minWidth: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    color: '#ffffff',
    backgroundColor: '#dc2626',
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  roomCreatePill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  roomCreateText: {
    color: '#2563eb',
    fontSize: 12,
    fontWeight: '800',
  },
  chatHeader: {
    marginHorizontal: 20,
    marginBottom: 10,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
    gap: 10,
  },
  roomDetailsScroll: {
    flexGrow: 0,
  },
  roomDetailsContent: {
    gap: 10,
    paddingBottom: 4,
  },
  roomHeaderActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roomTitleBlock: {
    gap: 2,
  },
  roomTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
  },
  roomSummary: {
    color: '#6b7280',
    fontSize: 12,
  },
  roomStatusBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  goalPanel: {
    gap: 10,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#f8fbff',
  },
  goalPanelHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  goalTitle: {
    color: '#1d4ed8',
    fontWeight: '900',
  },
  goalMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  goalActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    gap: 6,
  },
  goalPlanList: {
    gap: 8,
  },
  goalPlanItem: {
    gap: 5,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#ffffff',
  },
  goalAcceptance: {
    color: '#1e40af',
    fontSize: 12,
    lineHeight: 18,
  },
  goalReview: {
    color: '#374151',
    fontSize: 12,
    lineHeight: 18,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#eef2ff',
  },
  statusToken: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 7,
    borderWidth: 1,
  },
  statusTokenDefault: {
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  statusTokenRp: {
    borderColor: '#ddd6fe',
    backgroundColor: '#f5f3ff',
  },
  statusTokenMemory: {
    borderColor: '#99f6e4',
    backgroundColor: '#f0fdfa',
  },
  statusTokenWarning: {
    borderColor: '#fde68a',
    backgroundColor: '#fffbeb',
  },
  statusTokenText: {
    fontSize: 11,
    fontWeight: '800',
  },
  statusTokenTextDefault: {
    color: '#1d4ed8',
  },
  statusTokenTextRp: {
    color: '#6d28d9',
  },
  statusTokenTextMemory: {
    color: '#0f766e',
  },
  statusTokenTextWarning: {
    color: '#92400e',
  },
  rpSceneCard: {
    gap: 7,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ddd6fe',
    backgroundColor: '#faf5ff',
  },
  rpSceneHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  rpSceneTitle: {
    color: '#581c87',
    fontWeight: '900',
  },
  rpSceneBadge: {
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    color: '#6d28d9',
    backgroundColor: '#ede9fe',
    fontSize: 11,
    fontWeight: '800',
  },
  rpSceneTone: {
    color: '#7c3aed',
    fontSize: 12,
    fontWeight: '800',
  },
  rpSceneBody: {
    color: '#4c1d95',
    fontSize: 13,
    lineHeight: 20,
  },
  memberChips: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  memberChip: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
  },
  memberChipSelected: {
    backgroundColor: '#111827',
  },
  memberChipDisabled: {
    opacity: 0.45,
  },
  agentBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  agentAvatar: {
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
  },
  agentAvatarText: {
    fontWeight: '900',
  },
  agentStatusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
  },
  memberChipText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  memberChipTextSelected: {
    color: '#ffffff',
  },
  memberChipTextDisabled: {
    color: '#9ca3af',
  },
  quickPanel: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  panelLabel: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '800',
  },
  quickGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  quickCommand: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minWidth: 150,
    flexGrow: 1,
    padding: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  quickCommandDisabled: {
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  quickCommandTextBlock: {
    flex: 1,
    gap: 2,
  },
  quickCommandTitle: {
    color: '#111827',
    fontWeight: '700',
  },
  quickCommandTitleDisabled: {
    color: '#9ca3af',
  },
  quickCommandTarget: {
    color: '#6b7280',
    fontSize: 12,
  },
  toolsPanel: {
    gap: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  toolMetricRow: {
    flexDirection: 'row',
    gap: 8,
  },
  toolMetric: {
    flex: 1,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#f9fafb',
  },
  toolMetricValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
  },
  toolMetricLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  contextControl: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  stepper: {
    flexDirection: 'row',
    gap: 8,
  },
  toolActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roomEditPanel: {
    gap: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#f9fafb',
  },
  inlineFormRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inlineInput: {
    flex: 1,
  },
  memberEditorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  memberAliasInput: {
    flex: 1,
    minHeight: 38,
  },
  squareHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  squareCount: {
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    color: '#2563eb',
    backgroundColor: '#eff6ff',
    fontSize: 12,
    fontWeight: '800',
  },
  syncPanel: {
    gap: 10,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  settingsSubsection: {
    gap: 9,
  },
  settingsDivider: {
    height: 1,
    backgroundColor: '#e5e7eb',
  },
  diagnosticPanel: {
    gap: 10,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#f8fbff',
  },
  conflictPanel: {
    gap: 10,
    marginTop: 2,
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fed7aa',
    backgroundColor: '#fff7ed',
  },
  conflictHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  conflictWarning: {
    color: '#9a3412',
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
  },
  conflictList: {
    gap: 8,
  },
  conflictItem: {
    gap: 3,
    padding: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fed7aa',
    backgroundColor: '#ffffff',
  },
  conflictItemTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  conflictItemMeta: {
    color: '#9a3412',
    fontSize: 12,
    fontWeight: '700',
  },
  diagnosticList: {
    gap: 8,
  },
  diagnosticItem: {
    gap: 5,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  diagnosticHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  diagnosticLevel: {
    overflow: 'hidden',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: 11,
    fontWeight: '800',
  },
  diagnosticLevelInfo: {
    color: '#1d4ed8',
    backgroundColor: '#dbeafe',
  },
  diagnosticLevelSuccess: {
    color: '#166534',
    backgroundColor: '#dcfce7',
  },
  diagnosticLevelWarning: {
    color: '#92400e',
    backgroundColor: '#fef3c7',
  },
  diagnosticLevelError: {
    color: '#991b1b',
    backgroundColor: '#fee2e2',
  },
  diagnosticMessage: {
    color: '#374151',
    fontSize: 12,
    lineHeight: 18,
  },
  syncHeader: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 12,
  },
  syncHeaderText: {
    flex: 1,
    minWidth: 0,
  },
  syncToggle: {
    paddingHorizontal: 10,
    paddingVertical: 7,
    borderRadius: 999,
    backgroundColor: '#f3f4f6',
  },
  syncToggleOn: {
    backgroundColor: '#dcfce7',
  },
  syncToggleText: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '800',
  },
  syncToggleTextOn: {
    color: '#166534',
  },
  syncMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  squareEvent: {
    gap: 8,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  squareEventHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  squareEventSource: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  squareEventTitle: {
    color: '#111827',
    fontWeight: '800',
  },
  squareEventMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  messages: {
    flex: 1,
    paddingHorizontal: 20,
  },
  messagesContent: {
    gap: 10,
    paddingBottom: 18,
  },
  messageBubble: {
    alignSelf: 'flex-start',
    maxWidth: '92%',
    padding: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  userMessage: {
    alignSelf: 'flex-end',
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  systemMessage: {
    alignSelf: 'center',
    maxWidth: '100%',
    borderColor: '#fde68a',
    backgroundColor: '#fffbeb',
  },
  agentMessage: {
    borderColor: '#e0e7ff',
    backgroundColor: '#ffffff',
  },
  delegatedMessage: {
    borderColor: '#fed7aa',
    backgroundColor: '#fff7ed',
  },
  gmMessage: {
    borderColor: '#ddd6fe',
    backgroundColor: '#faf5ff',
  },
  rpCharacterMessage: {
    borderColor: '#fbcfe8',
    backgroundColor: '#fff1f2',
  },
  delegationBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    marginBottom: 8,
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 6,
    backgroundColor: '#f3f4f6',
    alignSelf: 'flex-start',
  },
  delegationText: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  messageBubbleWide: {
    maxWidth: 760,
  },
  messageMeta: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    marginBottom: 6,
  },
  authorBlock: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    flexShrink: 1,
  },
  messageRoleBadge: {
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    color: '#4b5563',
    backgroundColor: '#f3f4f6',
    fontSize: 10,
    fontWeight: '900',
  },
  author: {
    color: '#111827',
    fontWeight: '800',
  },
  status: {
    flexShrink: 1,
    color: '#6b7280',
    fontSize: 12,
    textAlign: 'right',
  },
  statusError: {
    color: '#b91c1c',
  },
  messageText: {
    color: '#1f2937',
    lineHeight: 22,
  },
  markdown: {
    gap: 8,
  },
  markdownText: {
    color: '#1f2937',
    lineHeight: 22,
  },
  markdownHeading: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: '800',
    color: '#111827',
  },
  markdownListRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  markdownBullet: {
    minWidth: 18,
    color: '#4b5563',
    fontWeight: '800',
    lineHeight: 22,
  },
  markdownListText: {
    flex: 1,
  },
  markdownQuote: {
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: '#bfdbfe',
  },
  markdownCodeBlock: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#111827',
  },
  markdownCodeText: {
    color: '#e5e7eb',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 12,
    lineHeight: 18,
  },
  markdownTable: {
    borderWidth: 1,
    borderColor: '#e5e7eb',
    borderRadius: 8,
    overflow: 'hidden',
  },
  markdownTableRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  markdownTableHeader: {
    borderTopWidth: 0,
    backgroundColor: '#f9fafb',
  },
  markdownTableCell: {
    flex: 1,
    minWidth: 80,
    paddingHorizontal: 8,
    paddingVertical: 7,
    color: '#1f2937',
    fontSize: 12,
    lineHeight: 18,
  },
  inlineCode: {
    borderRadius: 4,
    backgroundColor: '#eef2ff',
    color: '#3730a3',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 12,
  },
  inlineBold: {
    fontWeight: '800',
    color: '#111827',
  },
  streamingLine: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  streamingText: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  messageActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    marginTop: 10,
    gap: 8,
  },
  permissionPanel: {
    gap: 8,
    marginTop: 10,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#fde68a',
    backgroundColor: '#fffbeb',
  },
  permissionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  permissionTitleRow: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minWidth: 0,
  },
  permissionTitle: {
    flex: 1,
    color: '#78350f',
    fontWeight: '900',
  },
  permissionStatus: {
    overflow: 'hidden',
    paddingHorizontal: 7,
    paddingVertical: 3,
    borderRadius: 999,
    color: '#92400e',
    backgroundColor: '#fef3c7',
    fontSize: 11,
    fontWeight: '900',
  },
  permissionStatusDone: {
    color: '#166534',
    backgroundColor: '#dcfce7',
  },
  permissionBody: {
    color: '#451a03',
    fontSize: 13,
    lineHeight: 19,
  },
  permissionReason: {
    color: '#92400e',
    fontSize: 12,
    lineHeight: 18,
  },
  permissionActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  permissionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 32,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  permissionButtonPrimary: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  permissionButtonText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '900',
  },
  permissionButtonTextPrimary: {
    color: '#ffffff',
  },
  attachments: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 8,
    gap: 6,
  },
  attachmentPreview: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    maxWidth: 320,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ccfbf1',
    backgroundColor: '#f0fdfa',
  },
  attachmentThumb: {
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#ccfbf1',
  },
  attachmentIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 42,
    height: 42,
    borderRadius: 8,
    backgroundColor: '#ccfbf1',
  },
  attachmentInfo: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  attachmentName: {
    color: '#0f172a',
    fontSize: 12,
    fontWeight: '800',
  },
  attachmentSummary: {
    color: '#0f766e',
    fontSize: 11,
    lineHeight: 15,
  },
  attachmentModalOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    backgroundColor: 'rgba(15, 23, 42, 0.55)',
  },
  attachmentModalCard: {
    width: 760,
    maxWidth: '96%',
    maxHeight: '88%',
    borderRadius: 22,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    shadowColor: '#0f172a',
    shadowOpacity: 0.22,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  attachmentModalCardCompact: {
    width: '100%',
    maxHeight: '92%',
    borderRadius: 18,
  },
  attachmentModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    padding: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
    backgroundColor: '#f8fafc',
  },
  attachmentModalTitleBlock: {
    flex: 1,
    minWidth: 0,
  },
  attachmentModalTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '900',
  },
  attachmentModalMeta: {
    marginTop: 3,
    color: '#6b7280',
    fontSize: 12,
  },
  attachmentModalActions: {
    flexDirection: 'row',
    gap: 8,
  },
  attachmentModalBody: {
    maxHeight: 560,
  },
  attachmentModalBodyContent: {
    padding: 16,
  },
  attachmentPreviewImage: {
    width: '100%',
    minHeight: 300,
    borderRadius: 14,
    backgroundColor: '#f1f5f9',
  },
  attachmentPreviewText: {
    minHeight: 260,
    padding: 14,
    borderRadius: 14,
    color: '#111827',
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 13,
    lineHeight: 20,
    backgroundColor: '#f8fafc',
  },
  attachmentUnsupportedPreview: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    minHeight: 260,
    padding: 20,
    borderRadius: 14,
    backgroundColor: '#f8fafc',
  },
  attachmentUnsupportedTitle: {
    color: '#111827',
    fontSize: 15,
    fontWeight: '900',
  },
  attachment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#f0fdfa',
  },
  attachmentText: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '700',
  },
  composer: {
    paddingHorizontal: 14,
    paddingTop: 9,
    paddingBottom: 12,
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  mentionBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  mentionHint: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '800',
  },
  mentionList: {
    gap: 6,
  },
  mentionChip: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
  },
  mentionChipSelected: {
    backgroundColor: '#111827',
  },
  mentionChipDisabled: {
    opacity: 0.45,
  },
  mentionChipText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '700',
  },
  mentionChipTextSelected: {
    color: '#ffffff',
  },
  searchPanel: {
    gap: 8,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: '#e5e7eb',
  },
  searchInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 40,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  searchInput: {
    flex: 1,
    minHeight: 38,
    color: '#111827',
  },
  searchResults: {
    gap: 8,
  },
  searchResult: {
    gap: 4,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  searchResultActive: {
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  searchResultHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
  },
  searchResultTitle: {
    color: '#111827',
    fontWeight: '800',
  },
  searchResultMeta: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  searchResultSnippet: {
    color: '#4b5563',
    fontSize: 12,
    lineHeight: 18,
  },
  input: {
    minHeight: 44,
    maxHeight: 140,
    paddingHorizontal: 13,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
    color: '#111827',
  },
  importSection: {
    gap: 8,
    marginTop: 4,
  },
  importRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  editPanel: {
    gap: 8,
  },
  jsonPasteInput: {
    minHeight: 120,
    fontFamily: Platform.OS === 'ios' ? 'Menlo' : 'monospace',
    fontSize: 11,
  },
  modeShortcutList: {
    gap: 6,
    paddingRight: 4,
  },
  modeShortcut: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    minHeight: 30,
    paddingHorizontal: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  modeShortcutActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  modeShortcutText: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '700',
  },
  modeShortcutTextActive: {
    color: '#ffffff',
  },
  slashPanel: {
    gap: 8,
    padding: 9,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  slashCommandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
    padding: 8,
    borderRadius: 8,
    backgroundColor: '#ffffff',
  },
  slashCommandIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#f3f4f6',
  },
  slashCommandTitle: {
    color: '#111827',
    fontWeight: '800',
  },
  pendingAttachments: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pendingAttachmentRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    maxWidth: '100%',
  },
  pendingAttachmentPreviewCell: {
    flexShrink: 1,
  },
  pendingAttachment: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    backgroundColor: '#f0fdfa',
  },
  pendingAttachmentText: {
    color: '#0f766e',
    fontSize: 12,
    fontWeight: '700',
  },
  composerInputRow: {
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 7,
  },
  iconButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 40,
    height: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
  },
  iconButtonPrimary: {
    borderColor: '#2563eb',
    backgroundColor: '#2563eb',
  },
  composerInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 128,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#f9fafb',
    color: '#111827',
    lineHeight: 20,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 42,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: '#2563eb',
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '800',
  },
  secondaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 13,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d1d5db',
    backgroundColor: '#ffffff',
  },
  secondaryButtonText: {
    color: '#374151',
    fontWeight: '700',
  },
  miniButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  miniButtonText: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.45,
  },
  sectionTitle: {
    marginTop: 12,
    marginBottom: 4,
    fontSize: 18,
    fontWeight: '800',
    color: '#111827',
  },
  card: {
    padding: 14,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
    gap: 10,
  },
  managedRoomCard: {
    borderColor: '#bfdbfe',
    backgroundColor: '#f8fbff',
  },
  roomManagementPanel: {
    gap: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#ffffff',
  },
  roomMemberManageList: {
    gap: 8,
  },
  roomMemberManageRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  rowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 8,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#e5e7eb',
  },
  rowMain: {
    flex: 1,
    gap: 3,
  },
  cardTitle: {
    color: '#111827',
    fontWeight: '800',
    fontSize: 16,
  },
  muted: {
    color: '#6b7280',
  },
  help: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 18,
  },
  hint: {
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#fffbeb',
  },
  healthPanel: {
    gap: 12,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  healthPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  healthTitle: {
    color: '#111827',
    fontSize: 16,
    fontWeight: '800',
  },
  healthMetricRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  healthMetric: {
    flex: 1,
    minWidth: 86,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
  },
  healthMetricOk: {
    borderColor: '#bbf7d0',
    backgroundColor: '#f0fdf4',
  },
  healthMetricError: {
    borderColor: '#fecaca',
    backgroundColor: '#fef2f2',
  },
  healthMetricChecking: {
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  healthMetricUnknown: {
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  healthMetricValue: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
  },
  healthMetricLabel: {
    color: '#6b7280',
    fontSize: 12,
    fontWeight: '700',
  },
  connectionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  connectionBadges: {
    alignItems: 'flex-end',
    gap: 6,
  },
  badge: {
    overflow: 'hidden',
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: 999,
    fontSize: 12,
    fontWeight: '800',
  },
  badgeOn: {
    color: '#166534',
    backgroundColor: '#dcfce7',
  },
  badgeOff: {
    color: '#7f1d1d',
    backgroundColor: '#fee2e2',
  },
  healthBadgeOk: {
    color: '#166534',
    backgroundColor: '#dcfce7',
  },
  healthBadgeError: {
    color: '#991b1b',
    backgroundColor: '#fee2e2',
  },
  healthBadgeChecking: {
    color: '#1d4ed8',
    backgroundColor: '#dbeafe',
  },
  healthBadgeUnknown: {
    color: '#4b5563',
    backgroundColor: '#f3f4f6',
  },
  profileCard: {
    gap: 7,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  profileCardEmpty: {
    gap: 5,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  profileHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  profileTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  profileUpdated: {
    color: '#6b7280',
    fontSize: 11,
    fontWeight: '700',
  },
  profilePersona: {
    color: '#1e3a8a',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 18,
  },
  profileLine: {
    gap: 2,
  },
  profileLabel: {
    color: '#1d4ed8',
    fontSize: 12,
    fontWeight: '800',
  },
  profileText: {
    color: '#1f2937',
    fontSize: 12,
    lineHeight: 18,
  },
  healthDetails: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    padding: 10,
    borderRadius: 8,
    backgroundColor: '#f9fafb',
  },
  healthDetailText: {
    color: '#1f2937',
    fontSize: 12,
    fontWeight: '700',
  },
  healthCheckedAt: {
    color: '#6b7280',
    fontSize: 12,
  },
  buttonRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },

  collabPanel: {
    gap: 10,
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#f8fbff',
  },
  collabPanelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  summaryBox: {
    gap: 6,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd6fe',
    backgroundColor: '#f5f3ff',
  },
  summaryTitle: {
    color: '#5b21b6',
    fontSize: 12,
    fontWeight: '800',
  },
  taskList: {
    gap: 8,
  },
  taskCard: {
    gap: 6,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  taskTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  timelineList: {
    gap: 8,
  },
  timelineItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
  },
  timelineItemLarge: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f3f4f6',
  },
  timelineBody: {
    flex: 1,
    gap: 2,
  },
  timelineTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '800',
  },
  timelineMeta: {
    color: '#6b7280',
    fontSize: 11,
    lineHeight: 16,
  },
  emptyState: {
    alignItems: 'center',
    alignSelf: 'center',
    width: '100%',
    maxWidth: 440,
    gap: 10,
    paddingVertical: 34,
    paddingHorizontal: 20,
  },
  emptyIcon: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 44,
    height: 44,
    borderRadius: 8,
    backgroundColor: '#eff6ff',
  },
  emptyTitle: {
    color: '#111827',
    fontSize: 18,
    fontWeight: '800',
    textAlign: 'center',
  },
  emptyBody: {
    color: '#6b7280',
    lineHeight: 20,
    textAlign: 'center',
  },


  storageInfoBox: {
    gap: 5,
    padding: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  storageInfoTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '900',
  },
  storageInfoText: {
    color: '#4b5563',
    fontSize: 12,
    lineHeight: 18,
  },
  storageInfoPath: {
    color: '#6b7280',
    fontSize: 11,
    fontFamily: Platform.select({ web: 'monospace', default: undefined }),
  },
  onboardingPanel: {
    gap: 10,
    padding: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bfdbfe',
    backgroundColor: '#eff6ff',
  },
  onboardingStep: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    padding: 10,
    borderRadius: 10,
    backgroundColor: '#ffffff',
  },
  onboardingIndex: {
    width: 24,
    height: 24,
    borderRadius: 12,
    overflow: 'hidden',
    color: '#1d4ed8',
    backgroundColor: '#dbeafe',
    textAlign: 'center',
    lineHeight: 24,
    fontWeight: '900',
  },
  onboardingIndexDone: {
    color: '#166534',
    backgroundColor: '#dcfce7',
  },
  templateGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  templateCard: {
    flexGrow: 1,
    flexBasis: 220,
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#f8fbff',
  },
  modeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  roomModeCard: {
    flexGrow: 1,
    flexBasis: 132,
    minHeight: 92,
    gap: 6,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  roomModeCardActive: {
    borderColor: '#7c3aed',
    backgroundColor: '#f5f3ff',
  },
  roomModeTitle: {
    color: '#111827',
    fontSize: 13,
    fontWeight: '900',
  },
  roomModeTitleActive: {
    color: '#5b21b6',
  },
  roomModeDescription: {
    color: '#6b7280',
    fontSize: 12,
    lineHeight: 17,
  },
  roomModeDescriptionActive: {
    color: '#4c1d95',
  },
  archiveCard: {
    gap: 7,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#ddd6fe',
    backgroundColor: '#faf5ff',
  },
  buttonRowCompact: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
    justifyContent: 'flex-end',
  },
  taskBoardRow: {
    gap: 10,
    paddingVertical: 4,
  },
  taskBoardColumn: {
    width: 210,
    gap: 8,
    padding: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#f9fafb',
  },
  taskBoardTitle: {
    color: '#111827',
    fontSize: 12,
    fontWeight: '900',
  },
  taskBoardItem: {
    gap: 4,
    padding: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  drawerTaskColumn: {
    gap: 5,
    padding: 9,
    borderRadius: 8,
    backgroundColor: '#f9fafb',
  },
  relationCard: {
    gap: 8,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dbeafe',
    backgroundColor: '#ffffff',
  },
  relationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  relationArrow: {
    color: '#6b7280',
    fontSize: 16,
    fontWeight: '900',
  },
  rpSceneArchive: {
    color: '#6d28d9',
    fontSize: 12,
    fontWeight: '800',
    marginTop: 4,
  },
  shellDark: {
    backgroundColor: '#0f172a',
  },
  headerDark: {
    backgroundColor: '#0f172a',
  },
  titleDark: {
    color: '#f8fafc',
  },
  subtitleDark: {
    color: '#cbd5e1',
  },
  contentDark: {
    backgroundColor: '#0f172a',
  },
  focusedChatHeaderDark: {
    borderBottomColor: '#1f2937',
    backgroundColor: '#111827',
  },
  focusedChatMainDark: {
    backgroundColor: '#0f172a',
  },
  messageBubbleDark: {
    borderColor: '#334155',
    backgroundColor: '#111827',
  },
  composerDark: {
    borderTopColor: '#1f2937',
    backgroundColor: '#111827',
  },
  inputDark: {
    borderColor: '#334155',
    backgroundColor: '#0f172a',
    color: '#f8fafc',
  },
  mobileRoomCardDark: {
    borderColor: '#334155',
    backgroundColor: '#111827',
  },
  mobileDetailsCardDark: {
    borderColor: '#334155',
    backgroundColor: '#111827',
  },
  modePillRow: {
    gap: 8,
    paddingRight: 4,
  },
  modePill: {
    minHeight: 32,
    justifyContent: 'center',
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  modePillActive: {
    borderColor: '#2563eb',
    backgroundColor: '#eff6ff',
  },
  modePillText: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '800',
  },
  modePillTextActive: {
    color: '#1d4ed8',
  },
  mobileMemberManageChip: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    padding: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  inlineIconButton: {
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: 8,
    backgroundColor: '#eff6ff',
  },
  segmentedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  segmentedOption: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#e5e7eb',
    backgroundColor: '#ffffff',
  },
  segmentedOptionActive: {
    borderColor: '#111827',
    backgroundColor: '#111827',
  },
  segmentedOptionText: {
    color: '#4b5563',
    fontSize: 12,
    fontWeight: '800',
  },
  segmentedOptionTextActive: {
    color: '#ffffff',
  },
});

